;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(evil-append
                               evil-append-line
                               evil-insert
                               evil-previous-line
                               evil-yank
                               evil-delete
                               evil-next-line
                               evil-normal-state
                               evil-change
                               keyboard-quit
                               autopair-backspace
                               evil-forward-char
                               evil-backward-char))

(setq mc/cmds-to-run-once '(evil-forward-section-begin
                            reposition-window
                            evil-record-macro
                            cycle-buffer))

                            
                               
