;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
        evil-change
        ))

(setq mc/cmds-to-run-once
      '(
        mc/unmark-previous-like-this
        reposition-window
        ))
