;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all '(evil-previous-line
                               evil-yank
                               evil-delete
                               evil-next-line
                               evil-normal-state
                               evil-change
                               evil-forward-char
                               evil-backward-char))

(setq mc/cmds-to-run-once '(keyboard-quit))

                               
